# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('writer', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('is_show', models.BooleanField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
